{
    "openapi": "3.0.1",
    "info": {
        "title": "OpenAPI definition",
        "version": "v0"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/products": {
            "post": {
                "tags": [
                    "product-controller"
                ],
                "operationId": "createProduct",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ProductModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/ProductModel"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/contacts": {
            "get": {
                "tags": [
                    "contact-controller"
                ],
                "operationId": "getAllContacts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ContactModel"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "contact-controller"
                ],
                "operationId": "createContact",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ContactModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/ContactModel"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "tags": [
                    "categories-controller"
                ],
                "operationId": "getAllCategories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "categories-controller"
                ],
                "operationId": "createCategorie",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CategoryModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/categories/{name_category}/{id_product}": {
            "post": {
                "tags": [
                    "categories-controller"
                ],
                "operationId": "insertProductsInCategories",
                "parameters": [
                    {
                        "name": "name_category",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id_product",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/carousel": {
            "get": {
                "tags": [
                    "carousel-controller"
                ],
                "operationId": "getAllCarousel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/DataResponse"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "carousel-controller"
                ],
                "operationId": "createCarousel",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CarouselModel"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/DataResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/products/product": {
            "get": {
                "tags": [
                    "product-controller"
                ],
                "operationId": "getProductsWithQuery",
                "parameters": [
                    {
                        "name": "featured",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "name": "promotion",
                        "in": "query",
                        "required": false,
                        "schema": {
                            "type": "boolean"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/ProductModel"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/home": {
            "get": {
                "tags": [
                    "home-controller"
                ],
                "operationId": "getHome",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/HomeRecord"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/carousel/{id}": {
            "delete": {
                "tags": [
                    "carousel-controller"
                ],
                "operationId": "deleteCarousel",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/DataResponse"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "ProductModel": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "image_url": {
                        "type": "string"
                    },
                    "descrição": {
                        "type": "string"
                    },
                    "em_destaque": {
                        "type": "boolean"
                    },
                    "em_promoção": {
                        "type": "boolean"
                    }
                }
            },
            "AddressModel": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "cep": {
                        "type": "string"
                    },
                    "estado": {
                        "type": "string"
                    },
                    "cidade": {
                        "type": "string"
                    },
                    "lograuro": {
                        "type": "string"
                    },
                    "numero": {
                        "type": "string"
                    },
                    "bairro": {
                        "type": "string"
                    },
                    "complemento": {
                        "type": "string"
                    }
                }
            },
            "ContactModel": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "telefone_fixo": {
                        "type": "string"
                    },
                    "telefone_celular": {
                        "type": "string"
                    },
                    "telefone_ouvidoria": {
                        "type": "string"
                    },
                    "e-mail": {
                        "type": "string"
                    },
                    "endereco": {
                        "$ref": "#/components/schemas/AddressModel"
                    }
                }
            },
            "CategoryModel": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "image_url": {
                        "type": "string"
                    },
                    "descrição": {
                        "type": "string"
                    },
                    "produtos": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ProductModel"
                        }
                    }
                }
            },
            "CarouselModel": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "image_url": {
                        "type": "string"
                    },
                    "url_redirect": {
                        "type": "string"
                    }
                }
            },
            "DataResponse": {
                "type": "object",
                "properties": {
                    "data": {
                        "type": "object"
                    }
                }
            },
            "CategoryDTO": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "imageUrl": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "HomeRecord": {
                "type": "object",
                "properties": {
                    "categorias": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/CategoryDTO"
                        }
                    },
                    "produtos": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ProductModel"
                        }
                    },
                    "carrossel": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/CarouselModel"
                        }
                    },
                    "contato": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ContactModel"
                        }
                    }
                }
            }
        }
    }
}
